import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Plus, Sparkles } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { PriorityBadge } from '../components/Common/Badges'

export default function ProjectDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { getProject, tasksForProject, changeTaskStatus } = useApp()
  const project = getProject(id)
  if (!project) return <div className="card empty-state"><h3>Project could not be found.</h3><Link className="btn btn-primary" to="/projects">Return to Projects</Link></div>
  const tasks = tasksForProject(project.id); const completed = tasks.filter((task) => task.status === 'Completed').length; const progress = tasks.length ? Math.round(completed / tasks.length * 100) : 0
  return <div className="stack" style={{ gap: 'var(--space-6)' }}>
    <button className="btn btn-ghost" onClick={() => navigate('/projects')} style={{ alignSelf: 'flex-start', paddingLeft: 0 }}><ArrowLeft size={16} /> Return to Projects</button>
    <section className="card" style={{ padding: 'var(--space-6)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 20, flexWrap: 'wrap' }}><div><div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 8 }}><span className="badge badge-progress">Project #{project.id}</span><span className="text-muted text-sm">Created {project.createdAt}</span></div><h2 style={{ fontSize: 26, marginBottom: 10 }}>{project.name}</h2><p className="text-muted" style={{ maxWidth: 760, lineHeight: 1.65 }}>{project.description}</p></div><div className="row row-wrap" style={{ alignItems: 'flex-start' }}><Link className="btn btn-secondary" to="/ai-mentor"><Sparkles size={16} /> Ask AI Mentor</Link><Link className="btn btn-primary" to="/tasks"><Plus size={16} /> Add Task</Link></div></div><div style={{ marginTop: 28 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}><span className="text-muted text-sm">Overall progress</span><strong>{progress}%</strong></div><div className="progress"><div className="progress-bar" style={{ width: `${progress}%` }} /></div></div><div className="row row-wrap" style={{ marginTop: 24 }}><div><span className="text-muted text-sm">Technology stack</span><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 6 }}>{project.techStack.map((tech) => <span className="chip" key={tech}>{tech}</span>)}</div></div><div style={{ marginLeft: 'auto' }}><span className="text-muted text-sm">Tasks</span><p style={{ fontWeight: 600, marginTop: 6 }}>{completed} completed of {tasks.length}</p></div></div></section>
    <section className="card"><div className="card-header"><h2 className="card-title">Project Tasks</h2><Link className="btn btn-primary btn-sm" to="/tasks"><Plus size={14} /> Add Task</Link></div><div className="table-wrapper" style={{ border: 0, borderRadius: 0 }}><table className="data-table"><thead><tr><th>Task</th><th>Priority</th><th>Status</th><th>Updated</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><strong>{task.title}</strong><p className="text-muted text-sm">{task.description}</p></td><td><PriorityBadge priority={task.priority} /></td><td><select className="form-select" value={task.status} onChange={(e) => changeTaskStatus(task.id, e.target.value)} style={{ width: 130, padding: '5px 8px', fontSize: 13 }}><option>Pending</option><option>In Progress</option><option>Completed</option></select></td><td className="text-muted">{task.updatedAt}</td></tr>)}</tbody></table></div></section>
  </div>
}
